Feature/#6
YAPP-Github/21st-ALL-Rounder-Team-1-iOS pull request #11
Opened 2022-11-24 14:03 UTC by anyukyung

## 🧴 PR 요약
- StoreDetailScene에서 매장에 대한 상세 정보를 보여주는 View를 제작하였습니다.
- button 3개로 이루어진 부분은 UIStackView를 서브클래싱해서 커스텀하였습니다.
- 가로 길이가 전체 뷰의 1/4인 전화 버튼, 인스타그램 버튼에 0.25의 Multiplier를 적용해서 구현했습니다.
```swift
        [callButton, instagramButton].forEach { button in
            button.snp.makeConstraints {
                $0.width.equalToSuperview().multipliedBy(0.25)
            }
        }
```

<br>

#### 📌 변경 사항
변경사항 및 주의 사항(모듈 설치 등)을 적어주세요.

- UIView Extension으로 addSubviews 함수를 추가했습니다.
뷰 여러개를 하나씩 addSubview하거나 반복문을 사용해서 add해야하는 공수를 줄이기 위해
가변 파라미터로 view를 받아오고, 그것을 반복으로 추가해주도록 하는 함수입니다.
```swift
extension UIView {
    func addSubviews(_ views: UIView...) {
        for view in views {
            self.addSubview(view)
        }
    }
}
```
같은 맥락으로 stackView에 여러 개의 subview를 추가할 수 있는 addSubviews 함수를 추가했습니다.
```swift
extension UIStackView {
    public func addArrangedSubviews(_ view: UIView...) {
        view.forEach { self.addArrangedSubview($0) }
    }
}
```

아래와 같은 형태로 사용할 수 있습니다.
```swift
// view
addSubviews(storeNameLabel, storeAddressLabel, openStateLabel, separatorLine,
                    closeTimeLabel, mapButton, distanceLabel, storeInfoStackView)
// stackView
addArrangedSubviews(callButton, instagramButton, recommendedButton)
```

- UIView Extension으로 makeRounded 함수를 추가했습니다.
cornerRadaius와 관련된 단순 코드 중복을 방지하기 위해
clipsToBounds값을 true로 변경해주고, 전달된 radius값을 적용해주는 단순한 함수를 추가했습니다.
```swift
extension UIView {
    func makeRounded(radius: CGFloat) {
        self.clipsToBounds = true
        self.layer.cornerRadius = radius
    }
}
```
아래와 같은 방식으로 사용가능합니다.
```swift
        mapButton.makeRounded(radius: 22)
        storeInfoStackView.makeRounded(radius: 10)
```
<br>

작업중에 필요하다고 생각하다보니 바로 extension에 추가해버려서..
다음부터는 따로 이슈파고 작업하도록 할게요~!!😄

##### 📸 ScreenShot
PR과 관련된 화면을 첨부해주세요.

<img src="https://user-images.githubusercontent.com/70168249/203795900-89c44fa0-abfb-4a2b-9cd3-b67eda85ebbb.png" width="50%" height="50%">

##### ✅ PR check list
```
- commit message가 적절한지 확인해주세요. 
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제해주세요.
```

#### Linked Issue
close #6

2022-11-24 15:09 UTC, Neph3779 requested changes
안녕하세요 클로이! @anyukyung 
PR내용 잘 확인했습니다.
코멘트에도 적어드렸듯, 짧은 로직임에도 단순 가독성을 위해 extension을 사용하는 것은
맞지 않다고 생각되기에 이번에 PR을 보내준 extension들은 제 생각엔 사용하지 않는것이 맞다고 생각됩니다.
항상 고생해주셔서 감사합니다! 💪

2022-11-24 15:09 UTC, Neph3779 commented on RefillStation/RefillStation/Domain/StoreInfo.swift
> +}
distance에 Int type을 사용하기엔 위험해보입니다. (km단위로 서버에서 보내주는 경우 소숫점 아래가 모두 잘리므로)
Double type을 사용하는게 어떨까요? 🧐

2022-11-24 15:09 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfoView.swift
> +        addSubviews(storeNameLabel, storeAddressLabel, openStateLabel, separatorLine,
이 메서드에는 addSubview 작업이 포함되어 있으니 setUpConstraints라는 네이밍보단 
layout이라는 네이밍으로 통일하는게 어떨까요?

2022-11-24 15:09 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfoView.swift
> +    }
makeRounded 메서드를 처음본다면 extension에 구현된 구현부를 봐야하는 상황이 생깁니다.
간단하게 처리할 수 있는 로직이며 단순 가독성을 위해 extension을 사용하는건 불필요하다고 생각하고
코드 전반에 영향을 미치는 extension은 우선적으로 팀원간 합의가 필요하다고 생각해요
혼자 작업하는 프로젝트가 아닌 같이 작업하는 팀 프로젝트인걸 생각해주시면 좋을 것 같습니다.
합의되지 extension은 모두 걷어내는게 좋을 것 같습니다.

2022-11-25 19:51 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfoView.swift
> +    }
@Neph3779 말씀해주신 이유가 이해가 가서 요부분은 삭제하도록 하겠습니다
앞으로는 이런 부분은 좀 더 상의한 후에 추가할 수 있도록 할게요~!

2022-11-26 00:54 UTC, merged