[Feature/#109] Home, MyPage MockRepository를 통한 데이터 주입 및 화면 연결
YAPP-Github/21st-ALL-Rounder-Team-1-iOS pull request #110
Opened 2023-02-02 19:14 UTC by anyukyung

## 🧴 PR 요약
해당 pr에서 작업한 내역을 적어주세요.
- Home, MyPage MockRepository를 통한 데이터 주입 및 화면 연결을 구현했습니다.
- 하지만 MyPage에서 태그를 클릭해 넘어가는 부분은 이전 PR과 연관있는 부분이기에 빠른 구현을 위해 제외하고 구현했습니다.

#### 📌 변경 사항
변경사항 및 주의 사항(모듈 설치 등)을 적어주세요.

##### 📸 ScreenShot
PR과 관련된 화면을 첨부해주세요.

https://user-images.githubusercontent.com/70168249/216427656-5a2c47f8-2429-44b1-ae7d-1056fd5f8ad6.mov

##### ✅ PR check list
```
- commit message가 적절한지 확인해주세요. 
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제해주세요.
```

#### Linked Issue
close #109

2023-02-02 23:45 UTC, Neph3779 requested changes
@anyukyung 안녕하세요 클로이~!
새벽에도 열일하셨군요!!
남겨드린 코멘트 확인 부탁드립니다 🥰

2023-02-02 23:45 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/MyPageScene/MyPageViewController.swift
> +    }
didSelectRowAt같은 CollectionViewDelegate을 사용하지 않고 이렇게 처리하신 이유가 따로 있을까요❓❗️

2023-02-02 23:45 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/HomeScene/ViewModel/HomeViewModel.swift
> +}
위경도를 받아오는 로직은 추후에 제작될 예정일까요?
어떤식으로 받아오게 될지 정해져있으면 더 좋을 것 같아요! 
(이전 화면에서 의존성 주입을 받는다든가, 이 뷰모델에서 바로 가져오는 로직을 실행한다든가..)

2023-02-02 23:45 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/MyPageScene/MyPageViewController.swift
> +    }
applyDataSource는 마치 DiffableDataSource에서 사용되는 메서드를 바인딩 해주는 느낌이네요!.. 😅
setUpContents 정도가 어떨까요?
그리고 profileImageView의 이미지는 왜 nil인지도 궁금합니다!

2023-02-02 23:45 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/OnboardingScene/TermsDetailViewController.swift
> +    }
viewWillAppear에서는 tintColor 변경사항이 없는데
viewWillDisappear에서 tintColor를 변경해주는 이유가 있을까요?
뷰컨이 해당 뷰컨의 viewWillAppear tintColor를 변경한 경우에 viewWillDisappear에서 다시 원상복귀 시켜주고
화면을 나가는 것이 의도에 부합한다 생각해서 질문드려요!

2023-02-03 07:17 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/MyPageScene/MyPageViewController.swift
> +    }
@Neph3779 CollectionView가 아닌 UIView로 구현된 뷰라 이렇게 처리했습니다 ㅎ.ㅎ

2023-02-03 08:54 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/HomeScene/ViewModel/HomeViewModel.swift
> +}
@Neph3779 지금 추가 이슈에서 위도 경도 가져오는 부분을 진행중이어서 이 이슈에서 구현하려고 합니다!

2023-02-03 08:58 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/MyPageScene/MyPageViewController.swift
> +    }
@Neph3779 mockRepository에서 이미지 url이 지금은 빈 문자열로 내려오고 있고
추후 서버 작업 시 킹피셔를 통해 이미지를 불러올 생각으로 우선 nil로 처리해두었습니다..!!!

2023-02-03 09:25 UTC, anyukyung commented
@Neph3779 수정사항 반영했습니다! 코멘트도 확인해주시면 감사하겄습니다.. 🫡

2023-02-03 09:27 UTC, Neph3779 commented
@anyukyung 고생하셨습니다~ 깃 컨플릭트 해결해서 머지 부탁드려요~!!

2023-02-03 09:34 UTC, merged