Feature/#24 storeCollectinViewCell 및 HomeVC 추가
YAPP-Github/21st-ALL-Rounder-Team-1-iOS pull request #26
Opened 2022-11-30 15:14 UTC by anyukyung

## 🧴 PR 요약
- Store 도메인을 추가해서 StoreInfo가 Store를 가지고있도록 변경했습니다.
home에서 StoreDetail로 가는 Flow인데, 이 때 Store에 대한 data를 StoreDetailVC 전달해주면 불필요한 api호출을 줄일 수 있을 것 같아서 이런 식으로 바꾸게 되었습니다! 다른 의견 있으시다면 환영!!
(물론 아직 서버가 확정되지 않은 상태라 충분히 바뀔 가능성있음..)
- 또한 TableView로 만들려다 spacing 관리하기 더 편할 것 같은 CollectionView로 구현했습니다.
- HomeVC를 추가하고 거기에 테이블뷰를 얹어둔 상태입니다.
(다음 이슈에서 HomeVC 다른 부분 구현예정)
- 그리고 이번에 만든 storeCollectinViewCell의 하단 부분과 StoreDetailInfoview가
몇개 요소빼고 거의 같아서 커스텀뷰 하나로 합치려고 하다가,
지금은 뷰가 변동할 가능성이 클 것 같아서 일단은 따로 구현해둔 상태입니다!

#### 📌 변경 사항
변경사항 및 주의 사항(모듈 설치 등)을 적어주세요.

##### 📸 ScreenShot
PR과 관련된 화면을 첨부해주세요.
<img width="392" alt="스크린샷 2022-11-30 오후 10 17 43" src="https://user-images.githubusercontent.com/70168249/204833865-b1a2eec8-2718-40af-8f0d-5535c27e4261.png">

##### ✅ PR check list
```
- commit message가 적절한지 확인해주세요. 
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제해주세요.
```

#### Linked Issue
close #24

2022-11-30 16:03 UTC, Neph3779 requested changes
안녕하세요 클로이! @anyukyung 
우선 PR 메세지에 적어주신api 호출에 관한 부분은 
아직 서버의 명세가 나오지 않았기 때문에 구체적으로 알 수는 없지만

서버에서 상점에 대한 모든 data를 하나의 api를 통해 받아오는 것이 아닌
http 메서드의 head와 비슷하게 홈화면에서는 상점에 대해 필요한 정보들만 
compact하게 받아오는 api를 사용하고
store id를 통해 해당 상점의 data를 fetch하는 방향이 성능 측면에서 더 좋을 것 같습니다!

현재 진행중인 프로젝트는 서버와 교류를 활발히 할 수 있기에 
성능적으로 개선할 수 있는 부분은 미리 고민해서 서버측에 의견전달을 하는것도 
좋은 경험중 하나가 되지 않을까 싶습니다 😄 

사소하지만 몇가지 comment들이 달렸는데 
해당 comment들에 대해 의견 나누어보고 수정 거친뒤 merge하는게 좋을 것 같습니다!

바쁜 와중에도 고생해주셔서 감사합니다! :)

2022-11-30 16:03 UTC, sero3779 commented on RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
> +                                              collectionViewLayout: UICollectionViewFlowLayout())
storeCollectionView를 variable로 선언한 이유가 있으실까요?

2022-11-30 16:03 UTC, sero3779 commented on RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
> +        }
storeInfoView의 height를 고정하는 이유가 뭔가요?
dynamic하게 관리할수는 없을까요?

2022-11-30 16:03 UTC, sero3779 commented on RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
> +        }
추가로 storeInfoView가 별도로 분리된 이유도 궁금합니다~!

2022-11-30 16:03 UTC, sero3779 commented on RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
> +        }
저번 PR에서는 centerY가 아닌 다른 뷰의 topAnchor를 기준으로 layout을 설정하셨었는데
이번에는 centerY로 설정하신 이유가 궁금합니다~

2022-11-30 16:03 UTC, sero3779 commented on RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
> +        }
storeInfoView의 최하단에 위치한 view들 모두
bottomAnchor가 storeInfoView에 연결되지 않은 것 같은데
지난 PR에서도 제가 이 부분 수정한 기억이 있습니다!
bottomAnchor가 연결되어있지 않으면 dynamic한 높이계산이 되지  않으니 layout 잡으실때 
유의해주시면 감사하겠습니다~!!

2022-11-30 16:03 UTC, sero3779 commented on RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
> +        cell.render()
cell의 rendering 작업을 이 영역에서 해주는 이유가 있을까요?
cell의 prepareForReuse나 init시점이 아닌 이 지점에서 하는 이유가 궁금합니다~

2022-11-30 16:03 UTC, sero3779 commented on RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
> +    }
-32는 inset의 2배인 것으로 보이는데요
날것의 상수들을 enum으로 따로 관리하면 좋을 것 같습니다~!
inset의 2배인 경우 명시적으로 로직이 보이도록 코드를 써주시면 
다른사람이 읽었을때 더 쉽게 읽힐 것 같아요~!

2022-12-01 07:12 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
> +        }
@Neph3779
크게 이미지와 매장 정보 부분으로 컴포넌트가 나누어져있다고 생각했습니다. 그래서 ImageView와 하단 백그라운드 부분을 StoreInfoView로 나누었습니다! 그리고 StoreInfo에 대한 부분은 백그라운드 뷰에 추가해주었습니다.

셀안에서 storeInfoView 높이를 고정시킨 이유는 단순히 동적으로 늘어날 이유가 없을 것 같아서였는데,  이미 sizeForItemAt에서도 셀 전체 높이를 고정시켜뒀기 때문에 셀 안에서의 높이 고정은 불필요해보여서 라벨 기준으로 cosntraint를 잡아서 수정하도록 하겠습니다👍👍

2022-12-01 07:14 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
> +        }
ㅎㅎ 단순히 top, bottom의 제약조건을 두번 걸어주는 것보다 centerY로 한번 걸어주는게 결과도 같으면서 직관적인 것 같아서 이번에는 이런 식으로 걸어보았습니다.. 통일 시키는게 나은가 싶기도 하네요🤔

2022-12-01 07:23 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
> +        }
조금만 덧붙이자면 
cell의 size가 dynamic하다는게 반드시 run time에 셀이 늘어나는 것을 의미하는건 아니라 생각해요
내부의 요소들이 각자의 intrinsic or 지정된 contentsize를 가지고 cell의 contentView의
leading trailing top bottom에 연결되어 있다면 sizeForItemAt에서 직접적으로 cell의 size를 고정시켜주지 않아도
유연하게 cell sizing이 가능합니다~!

이미 결정된 cell size 내에 요소들을 넣다보면 
내부 요소가 잘리는 경우도 있을 것 같아요!
cell의 size가 static하게 fix된 경우(ex. ReviewWritingVC의 tagReviewCell)가 아니라면 
sizeForItemAt에서 cell의 전체 size를 고정시키지 않고 내부 constraint를 통해 해결해보는게 어떨까요?

현재의 코드로는 만약 기획이 수정되어 cell 내부 요소가 늘어난다면
직접 cell의 size를 확인한 뒤 sizeForItemAt에 가서 그 size에 맞는 값을 직접 넣어줘야 정상적으로 작동할 것 같아서요~!

2022-12-01 07:26 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
> +        }
모든 코드에는 메세지가 담겨있다고 생각해요 (야곰이 교육할때 항상 하는 말이에요)
같은 동작을 하는 코드라도 개발자의 의도가 어땠냐에 따라
해석하는 관점이 달라지기 마련이니까요 ㅎㅎ

같은 맥락에서 일관된 코드 작성은 중요하다 생각합니다!
이번 경우에도 "어떤 의도로 지난번과 달리 centerY를 사용한걸까?" 하는 생각을 하게 되었으니까요 ㅎㅎ

2022-12-02 10:08 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
> +        }
@Neph3779 cell을 automaticSize로 만들어서 내부에서 사이징하도록 수정했습니다!

2022-12-02 12:08 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
> +        let layout = UICollectionViewFlowLayout()
미처 이부분 깜빡하신게 아닐까 싶은데
let으로 바꿔서 머지 진행하도록 하겠습니다~!

2022-12-02 12:13 UTC, merged