[Feature/#64] LevelScene + PumpTagView 제작
YAPP-Github/21st-ALL-Rounder-Team-1-iOS pull request #66
Opened 2023-01-07 08:31 UTC by anyukyung

## 🧴 PR 요약
해당 pr에서 작업한 내역을 적어주세요.

- label로 이루어진 `PumpTagView` 컴포넌트를 추가했습니다. (네이밍 추천 환영🎊)
`setTitle` 메소드를 사용해서 title을 변경할 수 있습니다!
추후에 고민을 해보고 여러 태그 스타일 타입을 추가할 가능성이 있습니다.
<img width="295" alt="스크린샷 2023-01-07 오후 5 02 27" src="https://user-images.githubusercontent.com/70168249/211140535-33aac10e-3337-4288-abcd-de28f36e8953.png">

- `LevelScene`을 제작했습니다!
tableView로 제작하였으나, iOS15부터 생긴 paddingTop과 itemSpacing의 편의성으로 collectionView가 더 적합하다고 판단하여 변경하여 제작하였습니다!
<img width="423" alt="스크린샷 2023-01-07 오후 5 18 38" src="https://user-images.githubusercontent.com/70168249/211141105-532cdbb9-76d7-4ef5-a74b-54f11bcd8d43.png">

#### 📌 변경 사항
변경사항 및 주의 사항(모듈 설치 등)을 적어주세요.

##### 📸 ScreenShot
PR과 관련된 화면을 첨부해주세요.

##### ✅ PR check list
```
- commit message가 적절한지 확인해주세요. 
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제해주세요.
```

#### Linked Issue
close #64

2023-01-08 12:41 UTC, Neph3779 requested changes
@anyukyung 
리뷰 완료했습니다 클로이~!
코멘트 확인 부탁드려요!

2023-01-08 12:41 UTC, sero3779 commented on RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelHeaderView.swift
> +    }
줄간격 조정 부탁드려요~!

2023-01-08 12:41 UTC, Neph3779 commented on RefillStation/RefillStation/Domain/Entities/UserLevelInfo.swift
>      }
rawValue를 쓰기보단 연산프로퍼티를 쓰는게 어떨까요? 
네이밍이 붙으니 의미가 더 명확해질 것 같아서요!

2023-01-08 12:41 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelCollectionViewCell.swift
> +
서브 클래싱 예정이 없는 클래스라면 final 키워드 처리 부탁드려요!

2023-01-08 12:41 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/Component/PumpTagView.swift
> +    }
외부로 노출될 함수는 private 메서드 위에 작성하는게 좋을 것 같습니다!

2023-01-08 12:41 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/UserLevelScene/ViewController/UserLevelViewController.swift
> +    }()
isScrollEnabled가 false인 이유가 있을까요?

2023-01-08 12:41 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelHeaderView.swift
> +    }
이부분도 외부로 노출될 함수니 private 메서드 위로 가면 좋을 것 같습니다!

2023-01-08 12:41 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelHeaderView.swift
> +    }
<img width="467" alt="image" src="https://user-images.githubusercontent.com/67148595/211196342-cc846ff6-efd3-41c7-81e7-e4f8c8bb4ac9.png">
추가로 header view에 들어가는 remainingReviewTagView의 내용에는 "이상"이라는 단어가 포함되지 않고 현재까지 작성한 리뷰의 수를 보여주는거라 이해했는데 디자인팀에 문의해 확인해봐야 할 것 같습니다!

2023-01-08 12:41 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelCollectionViewCell.swift
> +    }
이 부분도 메서드 위치 조정해주세요~

2023-01-16 04:46 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/UserLevelScene/ViewController/UserLevelViewController.swift
> +    }()
@Neph3779 Horizontal로 잘못되어있는 부분과 함께 수정하였습니다 ㅎ 🥹

2023-01-16 05:02 UTC, anyukyung commented
@Neph3779 반영했습니다! 리뷰 감사합니다~ 👀

2023-01-16 05:17 UTC, Neph3779 requested changes
@anyukyung 
안녕하세요~ 클로이~
아주 약간의 수정 희망사항이 있어서 코멘트 남겨놓겠습니다~!!
감사합니다! ☺️

2023-01-16 05:17 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelCollectionViewCell.swift
> +
UserInfo.Level에 color, title을 연산프로퍼티로 만들어놓으면 어떨까요?
levelTitleLabel.text = level.name
levelTitleLabel.textColor = level.color
levelTagView.setTitle(level.tagTitle)
이런식으로 관리하면 raw한 string이 코드에서 돌아다니지 않게되니 더 좋을 것 같아요!

2023-01-16 05:17 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelCollectionViewCell.swift
>      static let reuseIdentifier = "levelCollectionViewCell"
```suggestion
    static let reuseIdentifier = String(decsribing: LevelCollectionViewCell.self)
```

2023-01-16 07:37 UTC, anyukyung commented
@Neph3779 최종 리뷰 부탁드립니다 ❗️

2023-01-16 07:41 UTC, Neph3779 approved these changes
@anyukyung  고생 많으셨습니다! 머지하겠습니다!

2023-01-16 07:42 UTC, merged