Feature/#67
YAPP-Github/21st-ALL-Rounder-Team-1-iOS pull request #68
Opened 2023-01-13 07:27 UTC by anyukyung

## 🧴 PR 요약
해당 pr에서 작업한 내역을 적어주세요.
- UInavigationBar에서 LargeTitle을 사용하거나 titleView를 생성해서 넣는 방법이 있는데, 두 방법 모두 height를 조정할 수는 없었습니다.
그래서 마이페이지에서도 똑같이 쓰이는 뷰이기 때문에, PupmLargeTitleNavigationBar 컴포넌트를 만들어 사용하였습니다.
- 플로팅 버튼을 추가하였습니다.
- 서치바가 없어짐에 따라 현재 위치를 나타내는 뷰를 기존 컬렉션뷰 헤더에 포함시켰습니다.

```
        // FIXME: 해당부분에 estimatedSize를 view의 frame을 계산해서 넣어주어야 Console에러가 나지 않습니다.
        // UICollectionViewFlowLayout.automaticSize의 height가 50이 반환되는것에 반해 실제 cell의 사이즈는 이보다 크기에
        // console에러가 발생하고 있습니다. 수정 부탁드립니다.
```
- FixMe 부분에 저는 해당 console 에러가 발생하지 않고, 뷰 계층에서도 레이아웃에 대해 깨지는 부분이 없었기 때문에 이부분 수정은 우선 보류해두었습니다.

https://user-images.githubusercontent.com/70168249/212261035-77e8c9a3-57cb-41e1-a367-ced05db41e4b.mov

#### 📌 변경 사항
변경사항 및 주의 사항(모듈 설치 등)을 적어주세요.

##### 📸 ScreenShot
PR과 관련된 화면을 첨부해주세요.

##### ✅ PR check list
```
- commit message가 적절한지 확인해주세요. 
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제해주세요.
```

#### Linked Issue
close #67

2023-01-15 12:16 UTC, anyukyung commented
@Neph3779 콘솔 에러 부분 fix하였습니다!

2023-01-15 17:46 UTC, Neph3779 requested changes
@anyukyung 클로이 고생 많으셨습니다!!
몇가지 코멘트가 있어서 확인 부탁드리겠습니다~!!! 😄

2023-01-15 17:46 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/Component/PumpLargeTitleNavigationBar.swift
> +}
외부에서 사용할 메서드는 상단에 배치하는게 좋을 것 같습니다! ☺️

2023-01-15 17:46 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/HomeScene/View/RegionRequestHeaderView.swift
> +    static let reuseIdentifier = String.init(describing: RegionRequestHeaderView.self)
init 명시는 의도된 것일까요?😄 
만약 아니라면 String(describing:) 으로 수정하면 좋을 것 같습니다!

2023-01-15 17:46 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/HomeScene/View/RegionRequestHeaderView.swift
>      }()
(단순 궁금증)
sizeToFit이 이곳에서 실행되었을때 결과물의 차이가 있나요??

2023-01-15 17:46 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
>              $0.top.leading.trailing.equalToSuperview()
현재 운영중 여부, 운영시간, dividerView는 2차 디자인 핸드오프 이후 삭제된 것으로 파악했습니다~!! 
따로 issue를 파서 pr을 보내실 예정이 아니시라면 이번에 같이 수정하는게 어떨까요?

2023-01-15 17:46 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
>      }()
정말 네비게이션 바는 아니고 네비게이션 바의 역할을 하는 view라
네이밍이 나중에 조~금 헷갈릴수도 있겠다는 생각이 드네요 ㅠㅠ...
HomeTitleBar등으로 변경하는게 어떨까요?!

2023-01-15 17:46 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
> +
addTarget보다 addAction을 통해 objc function없이 간편하게 액션 등록이 가능하니 참고 부탁드려요!! ☺️😄

2023-01-15 17:46 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
>          }
$0.leading.trailing.equalToSuperview()
$0.bottom.equalToSuperview()
두 문장 합칠수 있을 것 같습니다!

2023-01-16 07:42 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/HomeScene/View/RegionRequestHeaderView.swift
>      }()
@Neph3779 수정하다가 잘못 추가한 것 같습니다 💦 결과물은 똑같습니다!

2023-01-16 07:45 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
>              $0.top.leading.trailing.equalToSuperview()
오! 디바이더 뷰만 남은 상태라 눈치 못채고 있었는데 감사합니다~ 바로 수정하겠습니다

2023-01-16 08:07 UTC, anyukyung commented
@Neph3779 추가적인 리뷰 확인 후 변경사항 반영했습니다!

2023-01-16 08:10 UTC, Neph3779 approved these changes
@anyukyung  고생 많으셨습니다!! 머지하겠습니다~!

2023-01-16 08:10 UTC, merged