Feature/#53 운영정보탭제작 및 StoreDetail 화면 대규모 리팩토링
YAPP-Github/21st-ALL-Rounder-Team-1-iOS pull request #69
Opened 2023-01-14 16:03 UTC by Neph3779

## 🧴 PR 요약
- 운영정보 탭을 제작하였습니다.
- 기존의 복잡했던 cell providing 로직 개선과 여러곳에서 사용되는 run time dynamic cell height 적용을 위해 DiffableDataSource의 적용이 이루어졌습니다.
- 재활용되지 않음에도 불필요하게 많이 존재하던 셀들을 통합했습니다.
  - 리뷰 페이지의 상단 영역을 (태그리뷰 순위, 리뷰 작성하러가기 버튼 등) ReviewInfoCell로 통합했습니다.
  - 제품 카테고리를 선택하는 셀과 판매제품의 목록수를 나타내는 라벨을 ProductCategoriesCell로 통합했습니다.
- StoreDetailViewModel 내의 하위 viewModel들을 모두 StoreDetailViewModel에 통합했습니다.
  - 통합하여도 viewModel이 크게 복잡해지지 않기에 통합하였습니다.

## 📸 ScreenShot

### 판매제품 탭

| <img src="https://raw.githubusercontent.com/Neph3779/Blog-Image/forUpload/img/20230115005901.png" alt="Simulator Screen Shot - iPhone 14 - 2023-01-15 at 00.48.20" style="zoom:25%;" /> | <img src="https://raw.githubusercontent.com/Neph3779/Blog-Image/forUpload/img/20230115010233.png" alt="Simulator Screen Shot - iPhone 14 - 2023-01-15 at 01.02.09" style="zoom:25%;" /> |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
|                    **전체 카테고리 선택**                    |                    **개별 카테고리 선택**                    |

### 리뷰 탭

| <img src="https://raw.githubusercontent.com/Neph3779/Blog-Image/forUpload/img/20230115005910.png" alt="Simulator Screen Shot - iPhone 14 - 2023-01-15 at 00.48.25" style="zoom:25%;" /> | <img src="https://raw.githubusercontent.com/Neph3779/Blog-Image/forUpload/img/20230115005952.png" alt="Simulator Screen Shot - iPhone 14 - 2023-01-15 at 00.48.28" style="zoom:25%;" /> |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
|                       **Review Info**                        |                 **셀이 늘어났을 때의 모습**                  |

### 운영정보 탭

| <img src="https://raw.githubusercontent.com/Neph3779/Blog-Image/forUpload/img/20230115010106.png" alt="Simulator Screen Shot - iPhone 14 - 2023-01-15 at 00.48.33" style="zoom:25%;" /> | <img src="https://raw.githubusercontent.com/Neph3779/Blog-Image/forUpload/img/20230115010119.png" alt="Simulator Screen Shot - iPhone 14 - 2023-01-15 at 00.48.35" style="zoom:25%;" /> |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
|                   **더보기 버튼 탭 이전**                    |                   **더보기 버튼 탭 이후**                    |

#### Linked Issue

#53

2023-01-16 06:35 UTC, anyukyung requested changes

2023-01-16 06:35 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/RankView.swift
> +            $0.centerX.centerY.equalToSuperview()
같은 표현인데 `$0.center.equalToSuperview()`로 작성하면 더 간단하고 명확할 것 같습니다 ❗️

2023-01-16 06:35 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/ReviewInfoCell.swift
> +            for index in 1..<4 {
`for index in 1...3` 으로 안쓰시는 이유가 있을까요..!!

2023-01-16 06:35 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/ReviewInfoCell.swift
> +            $0.leading.trailing.equalToSuperview().inset(53)
top/leading/trailing/bottom 제약조건이 다 잡혀있어서 center 관려련 제약조건은 없어도 될 것 같은데, 따로 이유가 있을까요?!

2023-01-16 06:35 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/StoreDetailScene/View/TabBar/StoreDetailTabBarCell.swift
> +        reviewButton.titleLabel?.font = UIFont.font(style: .bodyLarge)
`.titleMedium`이 되어야할 것 같습니다!

2023-01-16 06:35 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/StoreDetailScene/View/TabBar/StoreDetailTabBarCell.swift
> +            $0.leading.equalTo(productListButton.snp.leading)
`$0.leading.equalTo(productListButton)` 으로 같은 표현이 가능합니다 👀

2023-01-16 06:35 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
> +                return UIImage(systemName: "hand.thumbsup")
이거 현재 Asset에 아이콘 이미지 없나요?!

2023-01-16 06:36 UTC, anyukyung commented
@Neph3779 아주 그냥 길고 길었던 여정 .. 🥲
리팩토링 하느라 너무 수고하셨습니다!
간단하게 리뷰 완료했습니다!

2023-01-16 07:50 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/ReviewInfoCell.swift
> +            for index in 1..<4 {
큰 이유는 없고 C언어때부터 for문 쓰던 습관인 것 같습니다~.. 
1...3으로 수정하는게 가독성 측면에서 더 좋을까요?

2023-01-16 07:51 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/ReviewInfoCell.swift
> +            $0.leading.trailing.equalToSuperview().inset(53)
불필요한 제약조건이라 삭제했습니다!

2023-01-16 08:02 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/StoreDetailScene/View/TabBar/StoreDetailTabBarCell.swift
> +        reviewButton.titleLabel?.font = UIFont.font(style: .bodyLarge)
@anyukyung  선택되지 않은 항목은 titleMedium2로 설정해야하는데
피그마에서 해당 폰트가 보이질 않네요 ㅠ.. 혹시 시간될때 확인해주시면 감사하겠습니다~

2023-01-16 08:07 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
> +                return UIImage(systemName: "hand.thumbsup")
link 버튼 이미지가 없어서 해당 에셋 추가하고 수정했습니다~!

2023-01-16 08:09 UTC, Neph3779 commented
@anyukyung 피드백 반영, 코멘트 확인 완료했습니다!!

2023-01-16 09:11 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/StoreDetailScene/View/TabBar/StoreDetailTabBarCell.swift
> +        reviewButton.titleLabel?.font = UIFont.font(style: .bodyLarge)
해결했습니다~!

2023-01-18 10:23 UTC, Neph3779 commented
@anyukyung 리뷰 내용 반영 및 2차디자인 변경사항들을 반영했습니다~!
아래는 아직 반영하지 않은 내역과 그 설명입니다!
<img width="326" alt="image" src="https://user-images.githubusercontent.com/67148595/213146443-23e170fe-0df5-4d0f-b9b9-b9c69729f9b4.png">
- 위의 화면의 매장상황에 따라 운영정보가 달라질 수 있다는 라벨은 개발 도중 추가된 UI라 추후 반영 예정입니다~
![image](https://user-images.githubusercontent.com/67148595/213146711-10fe3cda-84b0-4f46-aab7-36d19199e8f5.png)
- pop up의 경우 공통 컴포넌트로 뺄 예정이므로 신고 버튼과 팝업창은 제작하지 않았습니다. (가게 link가 등록되지 않았을 경우에 노출할 팝업도 마찬가지)
- Sticky Header의 경우 작업의 난이도가 높은데에 반해 중요도가 낮아 후순위로 미루어두었습니다. 추후에 따로 이슈를 파서 제작해볼 예정입니다.

리뷰 부탁드려요~!

2023-01-18 13:25 UTC, anyukyung approved these changes
고도의 집중력으로 읽진 못했지만.. ㅎㅎ
짧은 코멘트 남겨두었어요.. 리팩토링 하느라 수고하셨습니다..!

2023-01-18 13:25 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/StoreDetailScene/View/OperationInfo/OperationInfoCell.swift
> +    static let reuseIdentifier = "operationInfoCell"
이 부분도 String describe 사용하면 좋을 것 같습니다!

2023-01-18 13:41 UTC, Neph3779 commented
@anyukyung 반영 완료했습니다!

2023-01-18 13:41 UTC, merged