Feature/#80 [공통컴포넌트] PopUp VC 제작
YAPP-Github/21st-ALL-Rounder-Team-1-iOS pull request #81
Opened 2023-01-22 12:52 UTC by Neph3779

안녕하세요 클로이~ @anyukyung 
공통 컴포넌트인 pop up vc가 제작 완료되어 pr 보냅니다~

## 🧴 PR 요약
- 앱 내에서 공용으로 사용할 PopUpVc를 제작하였습니다.
- init을 통해 title과 description을 받아서 적용하며 imageView, textView를 configurationHandler와 함께 추가할 수 있습니다.
- closeButton의 경우 메서드를 통해 추가 할 수 있는데, titleLabel과 너무 딱 붙는것을 막기 위해 closeButton이 추가되면 titleLabel의 textAlignment를 center에서 natural로 다시 변경해주었습니다.
- titleLabel과 descriptionLabel의 font는 내부 변수인 titleFont와 descriptionFont를 조절하여 변경 가능합니다.

## 📸 ScreenShot

| <img src="https://raw.githubusercontent.com/Neph3779/Blog-Image/forUpload/img/20230122214739.png" alt="Simulator Screen Shot - iPhone 13 Pro - 2023-01-22 at 21.29.41" style="zoom:50%;" /> | <img src="https://raw.githubusercontent.com/Neph3779/Blog-Image/forUpload/img/20230122214742.png" alt="Simulator Screen Shot - iPhone 13 Pro - 2023-01-22 at 21.30.56" style="zoom:50%;" /> | <img src="https://raw.githubusercontent.com/Neph3779/Blog-Image/forUpload/img/20230122214744.png" alt="Simulator Screen Shot - iPhone 13 Pro - 2023-01-22 at 21.45.51" style="zoom:50%;" /> |
| :----------------------------------------------------------: | :----------------------------------------------------------: | :----------------------------------------------------------: |
|                        ImageView 삽입                        |                      Title이 없는 경우                       |                        textView 삽입      

#### Linked Issue
close #80

2023-01-22 18:45 UTC, anyukyung requested changes
리뷰 완료했습니다! 고생하셨습니다!

2023-01-22 18:45 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/Component/PumpPopUpViewController.swift
> +    }()
label의 text 색상을 지정해주어야 할 것 같아요!
그런데 탈퇴 팝업만 descriptionLabel이 다른 색상이라 따로 처리를 하거나,
외부에서 color를 바꿀 수 있도록 해야할 것 같습니다!

2023-01-22 18:45 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/Component/PumpPopUpViewController.swift
> +        let ctaButton = CTAButton()
제가 CTAButton을 더 범용적으로 사용하기위해서 내부에 type을 추가했는데..!
button의 타입을 따로 매개변수로 받아서 버튼을 추가해야할 것 같아요..!
#73 이슈가 머지가 되어야 수정 가능한 부분이라 이부분은 제가 추후 pr에서 반영해도 될 것 같긴 합니다!

2023-01-23 03:10 UTC, Neph3779 commented
@anyukyung 
반영 완료했습니다~!
폰트, 색상 등 다양한 요소들을 변경하는 경우에 대비하여 configurationHandler를 만들어주었습니다~
기본 title, description의 font와 색상이 fix되면 최대한 이 틀에서 벗어나지 않는 것이 좋다고 판단되어
configurationHandler를 외부 변수로 두었습니다. (imageView와 textView 추가시 메서드의 인자로 받던것과 대조되게 만들었습니다.)

2023-01-23 07:34 UTC, merged