Feature/#73 온보딩 닉네임 설정, 프로필 수정 뷰 제작
YAPP-Github/21st-ALL-Rounder-Team-1-iOS pull request #82
Opened 2023-01-22 18:00 UTC by anyukyung

## 🧴 PR 요약
해당 pr에서 작업한 내역을 적어주세요.

- CTAButton에 style을 추가하였습니다
   - basic 
   <img width="585" alt="스크린샷 2023-01-23 오전 2 15 29" src="https://user-images.githubusercontent.com/70168249/213929950-d1788296-f68c-4cdc-a7e3-bffe13066342.png">

    - cancel
    <img width="165" alt="스크린샷 2023-01-23 오전 2 16 05" src="https://user-images.githubusercontent.com/70168249/213929957-0d5fd369-e4ca-46c7-b72b-79615b45eedf.png">

    - doubleCheck
    <img width="122" alt="스크린샷 2023-01-23 오전 2 16 02" src="https://user-images.githubusercontent.com/70168249/213929954-dff57d98-6319-4150-9a3c-2f4b31910053.png">

- NicknameViewController를 제작하였습니다
   - VC의 type은 onboarding과 mypage로 나뉩니다.
   - 유효한 닉네임 string인지 판별하는 기준은 동일하기에 정규표현식을 사용해 한글,영문,숫자 그리고 백스페이스만 입력이 가능하도록 제한하였습니다. (특수문자를 포함한 그 외 문자들은 입력 불가)
  - 중복확인 버튼은 연속적으로 터치할 경우에 발생할 수 있는 불필요한 api 호출을 막기위해 
  - 최초 터치시에만 중복확인을 하고, DispatchWorkItem를 3초 주기로 cancle하여 터치 후 3초간은 중복확인을 하지 않도록 하였습니다.

#### 📌 변경 사항
변경사항 및 주의 사항(모듈 설치 등)을 적어주세요.

##### 📸 ScreenShot
PR과 관련된 화면을 첨부해주세요.
https://user-images.githubusercontent.com/70168249/213931758-4cedf569-94a3-4697-8392-5a9ce791c412.mov
https://user-images.githubusercontent.com/70168249/213931762-8c4bbfe4-c3bc-4f62-8196-83d61b65e10a.mov
<img width="374" alt="스크린샷 2023-01-23 오전 2 55 54" src="https://user-images.githubusercontent.com/70168249/213931895-cd5e6e82-5933-4f0f-9530-bd50f4cc0a0c.png">

##### ✅ PR check list
```
- commit message가 적절한지 확인해주세요. 
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제해주세요.
```

#### Linked Issue
close #73

2023-01-23 08:54 UTC, anyukyung commented
@Neph3779 바텀시트 추가 작업 완료했습니다! 👀

2023-01-23 09:42 UTC, Neph3779 requested changes
@anyukyung 고생 많으셨습니다~
> PopUpViewController로 분리할 경우 핸들러를 또 추가해야하고, 선택한 사진이나 삭제 여부를 이전 뷰컨트롤러로 전달해야하는 과정까지 필요하기 때문에 단순 View로 제작하여 넣었는데 더 좋은 방법이 있다면 리뷰에 써주심 감사하겠습니다~!! 👀

이 부분은 coordinator 패턴을 사용해서 관리하면 될 것 같습니다~

phpicker를 사용했을때 selection limit이 1개면
add 버튼이 아예 노출이 안되는 문제가 있습니다 🥲
하나의 이미지만을 선택하는 경우이므로 
이번에는 UIImagePickerController를 사용하는게 더 좋을 것 같습니다!

코멘트가 조금 많은데 차근차근 읽어보시고 
잘 이해가 안가시는 코멘트는 멘션 부탁드립니다!

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/Component/CTAButton.swift
> +    }
doubleCheck이라는 케이스는
특정 상황에서 사용되는 "기능"에 대한 이름이라 생각이 되어요 😆
basic과 cancel만을 두고 basic의 isEnabled 여부에 따른 색상변화를 커스텀할 수 있도록 만드는게 어떨까요?

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/Component/CTAButton.swift
> +
Style Enum의 내부 변수로 필요한 인자들을 넣어두면
세개의 메서드가 아닌 style을 인자로 받는 하나의 메서드로 처리할 수 있을 것 같아요~!

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/Component/CTAButton.swift
>  }
이 부분도 switch문을 열지 않더라도 style을 인자로 받아 한번에 처리해줄 수 있을 것 같습니다 😋

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/View/EditProfileBottomSheetView.swift
> +
pop up의 경우 view controller로 제작되어있기에
bottom sheet를 view로 제작할 경우 일관성이 없어보일 수 있을 것 같습니다! 🥲
ViewController로 제작하고 coordinator에서 화면전환에 대해 관리하는게 어떨까요?

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/View/EditProfileBottomSheetView.swift
> +    }()
lazy var을 사용하였다면 addTarget보다 addAction을 사용하는게 메서드 수가 줄어서 더 깔끔할 것 같아요!

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/View/EditProfileBottomSheetView.swift
> +        button.addTarget(self, action: #selector(DeleteButtonDidTapped), for: .touchUpInside)
요 부분도 addAction이 더 좋을 것 같습니다~!

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/View/EditProfileBottomSheetView.swift
> +        layer.maskedCorners = CACornerMask(arrayLiteral: .layerMinXMinYCorner, .layerMaxXMinYCorner)
```suggestion
        layer.maskedCorners = [.layerMinXMinYCorner, .layerMaxXMinYCorner]
```

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
> +    private var viewType: ViewType
저는 viewType은 ViewModel에 있어야할 변수라고 생각되는데 클로이는 어떻게 생각하시나요?

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
> +        phPickerViewController.delegate = self
lazy var로 지정해주었으면 클로저를 통한 생성 파트에서 delegate 지정을 해줘도 될 것 같습니다!

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
> +        var topView: UIView
layout 관해 전반적으로 살펴보았을때
바깥을 감싸는 StackView를 하나 둔 뒤
viewType에 따라 stack에 삽입하는 view 순서를 바꿔주는게 훨씬 깔끔할 것 같습니다~!

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
> +    }
이 부분도 Enum을 통해 메서드 하나로 통합할 수 있을 것 같아요!

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
> +}
이 로직은 ViewModel에 있어야 할 로직인 것 같습니다!

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
> +        }
이 로직은 text.count를 viewModel에 넘겨주어
viewModel 내에서 valid 여부를 체크한 뒤
Enum으로 상태를 반환하는게 좋아보입니다! (case underTwoChar, case overTenChar, case empty 등)

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
> +        }
반환된 enum case를 하나의 메서드에 넘겨주어 (setNickname(case: Case) 같은 꼴로)
그 내부에서 switch문을 통해 처리하는게 깔끔할 것 같습니다!

2023-01-23 09:42 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
> +        if string.hasVaildCharacters() || isBackSpace == -92 { return true }
이 부분도 viewModel로 로직을 뺄 수 있을 것 같습니다!

2023-01-25 07:32 UTC, anyukyung commented
@Neph3779
phpicker 사용시 add 버튼이 노출되지 않는 것은 `selection limit`이 1이기 때문입니다!
한장 선택시 바로 자동으로 picker가 dismiss되며, 디자인 측에서 권한 요청이 없는 phpicker를 선호해서 이 부분은 수정없이 진행했습니다!

그리고 CTAButton의 Style case 부분은 중복확인 버튼이 재사용되지 않음에 따라 doubleCheck 케이스 자체를 삭제하였습니다.
스택뷰를 포함한 나머지 부분의 리팩토링을 진행하였으니 확인 부탁드립니다! 🙌

2023-01-25 08:30 UTC, Neph3779 requested changes
@anyukyung 안녕하세요 클로이! 고생많으셨습니다!!

아래의 사진처럼 중복확인을 거치지 않은 경우에도 완료, 다음 버튼의 색상이 enable로 보이고 있는 문제가 있습니다! 
| ![Simulator Screen Shot - iPhone 13 Pro - 2023-01-25 at 17.15.01](https://raw.githubusercontent.com/Neph3779/Blog-Image/forUpload/img/20230125172651.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2023-01-25 at 17.17.13](https://raw.githubusercontent.com/Neph3779/Blog-Image/forUpload/img/20230125172658.png) |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
|                          마이페이지                          |                            온보딩                            |

추가로 기획에선 허용되지 않는 문자가 입력되었을때 아래의 사진처럼
사용할 수 없다고 표기하기를 원하는것에 반해 현재 앱의 구동은
아예 허용되지 않는 문자가 타이핑 되지 않고 있습니다 🥹
이 부분도 수정해주시면 좋을 것 같습니다!!

<img width="316" alt="image" src="https://user-images.githubusercontent.com/67148595/214515136-4a1edf26-40ac-4798-9469-a487933d748b.png">

그럼 이번에도 잘 부탁드려요! 😁

2023-01-25 08:30 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/ViewController/EditProfileBottomSheetViewController.swift
> +        }, for: .touchUpInside)
이 부분 deleteProfileImage가 완료된 후에 dismiss하지 않아도 문제 없는 것 맞을까요?

2023-01-25 08:30 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/Component/CTAButton.swift
```swift
    private var buttonTitleColor: UIColor {
        switch (style, isEnabled) {
        case (.basic, true):
            return .white
        case (.basic, false):
            return Asset.Colors.gray4.color
        case (.cancel, _):
            return Asset.Colors.gray6.color
        }
    }

    private var buttonBackgroundColor: UIColor {
        switch (style, isEnabled) {
        case (.basic, true):
            return Asset.Colors.primary10.color
        case (.basic, false):
            return Asset.Colors.gray2.color
        case (.cancel, _):
            return Asset.Colors.gray2.color
        }
    }
```

Style과 isEnabled(혹은 state)를 결합하여 위처럼 사용하면
버튼에 따라 메서드를 구분할 필요 없이 아래처럼 사용할 수 있을 것 같아요!

```swift
    private func setUpButtonColors() {
        backgroundColor = buttonBackgroundColor
        setTitleColor(buttonTitleColor, for: state)
    }
```

2023-01-25 08:30 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
>          }
상태에 따라 변화해야하는 텍스트이니 연산프로퍼티로 텍스트 내용을 빼는게 어떨까요?
```swift
     descriptionLabel.text = nicknameState.text
     switch nicknameState {
        case .empty:
            setEmptyNickname()
        case .underTwoCharacters, .overTenCharacters:
            setIncorrectNickname()
        case .correct:
            setCorrectNickname()
        }
```
위의 코드처럼 리팩토링이 가능할 것 같아요!

2023-01-25 08:30 UTC, Neph3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/ViewModel/NicknameViewModel.swift
>      var isVaild = true
이 변수는 사용되지 않고 있는 것 같습니다!

2023-01-26 10:07 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/NicknameScene/ViewModel/NicknameViewModel.swift
>      var isVaild = true
`isVaild` 변수를 말씀하시는 거라면 임시로 중복확인 여부 체크하는데 사용하고 있습니다 !

2023-01-26 12:19 UTC, anyukyung commented on RefillStation/RefillStation/Presentation/NicknameScene/ViewController/EditProfileBottomSheetViewController.swift
> +        }, for: .touchUpInside)
클로저 deleteProfileImage가 완료되기 이전에 dismiss가 되진 않을 것 같습니다 !

2023-01-26 15:45 UTC, anyukyung commented
@Neph3779 
특수문자에 경우에는 오프라인에서 아예 막는것도 괜찮겠다는 얘기를 했었어서 그렇게 진행했었는데,
한번 더 확인이 필요할 것 같아요! 크리티컬한 부분은 아니라, 한번 더 체크 후 문제가 된다면 추가적인 이슈에서 수정하겠습니다!

또 취소 버튼 디자인이 아래처럼 바뀌어서 그부분을 반영했습니다.
더불어 CTAButton을 제안해주신 방법처럼 연산 프로퍼티를 활용해 리팩토링했습니다!
<img width="207" alt="스크린샷 2023-01-27 오전 12 39 20" src="https://user-images.githubusercontent.com/70168249/214879687-a48343a1-310d-40f7-b879-c9fa0563b843.png">

완료, 혹은 다음 버튼은

1. 온보딩일 경우 (다음 버튼)
a. 닉네임이 valid 일 때 활성화
b. 닉네임이 invalid 일 때 비활성화
c. 텍스트필드가 변경될 때 비활성화

2. 마이페이지일 경우 (완료 버튼)
a. 이미지를 바꿨는데 닉네임이 valid 일 때 활성화
b. 이미지를 바꿨는데 닉네임이 Invalid 일 때 비활성화
c. 닉네임이 valid 할 때 활성화
d. 닉네임이 invalid 할 때 비활성화
e. 텍스트필드가 변경될 때 비활성화

이렇게 처리해주었습니다..!

2023-01-26 18:56 UTC, Neph3779 approved these changes
@anyukyung 고생 많으셨습니다!!!
viewModel이 var로 선언되어있는 부분과
Git conflict만 수정해서 머지해주시면 감사하겠습니다! 😄

2023-01-26 18:56 UTC, sero3779 commented on RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
> +    private var viewModel: NicknameViewModel
변수로 선언될 이유가 없는 것 같습니다!

2023-01-27 07:27 UTC, merged